# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

git:
  depth: 3

os:
  - linux

sudo: required

r_packages:
  - knitr
  - covr

apt_packages:
  - libudunits2-dev

after_success:
  - Rscript -e 'devtools::install_github("jimhester/covr")'
  - Rscript -e 'covr::codecov()'

warnings_are_errors: false
