#' Orgviz shiny UI
#'
#' @return shiny ui object
#' @import shiny
#' @export
#'
#' @examples
#' NULL
orgviz_ui <- function() {

  fluidPage(

    # Application title
    titlePanel("Orgsurveyr Shiny App"),

    # Sidebar with a slider input for number of bins
    sidebarLayout(
      sidebarPanel(
        checkboxInput('is_circular', 'Circularlize?:', value = FALSE),
        checkboxInput('is_dendrogram', 'Dendrogram?:', value = TRUE),
        uiOutput('var_ui'),
        uiOutput('root_unit'),
        actionButton("button", "Create new org plot")
      ),

      # Show a plot of the generated distribution
      mainPanel(
        plotOutput("plot")
      )
    )
  )

}

#' Orgviz shiny server
#'
#' @param input shiny input
#' @param output shiny output
#' @param tg user supplied tbl_graph
#' @param df user supplied a data frame in org_tall_df format
#'  ie summarised metrics for the units in the network as generated by calc_summary_df.
#'
#' @return shiny server function
#' @export
#'
#' @examples
#' NULL
orgviz_server <- function(input, output, tg=NULL, df=NULL) {

  if(is.null(tg)) {
    set.seed(10001)
    tg <- create_realistic_org(5, 5, prob=0.2) %>%
      simulate_unit_size()
  }

  if(is.null(df)) {
    # simulate individual data and summarise
    indiv_df <- tg %>%
      simulate_individuals_df() %>%
      dplyr::mutate(test_var2 = purrr::map_dbl(individual_id, ~rnorm(1, 20,3)))

    df <- calc_summary_df(tg, indiv_df, NULL,
                    c('test_var', 'test_var2'), TRUE)

  }

  var_list <- df %>% dplyr::distinct(metric_id) %>% unlist() %>% unname()

  values <- reactiveValues(
    selected_var = var_list[1],
    selected_node = '1'
    )

  observeEvent(input$root_unit, {
    values$selected_node <- input$root_unit
  })

  output$var_ui <- renderUI({
    selectInput('plot_var', 'Select a variable to plot', choices = var_list, selected = var_list[2])
  })

  tg_filtered <- reactive({

    nodes <- tg %>% tidygraph::activate(nodes) %>%
      tidygraph::as_tibble()

    sn <- which(nodes$unit_id == values$selected_node)

    tg %>%
      tidygraph::filter(tidygraph::node_distance_from(sn) < Inf)

  })

  output$plot <- renderPlot({

      plot_org(tg_filtered(), fill_var=input$plot_var, df=df,
               is_circular = input$is_circular, is_dendrogram = input$is_dendrogram)

  })

  output$root_unit <- renderUI({

    dept_info <- tg %>%
      tidygraph::filter(!tidygraph::node_is_leaf()) %>%
      tidygraph::activate(nodes) %>%
      tidygraph::as_tibble() %>%
      dplyr::arrange(unit_id)

    choices_vector <- dept_info$unit_id
    names(choices_vector) <- dept_info$unit_id

    selectInput(
      'root_unit',
      'Choose an organisational unit',
      choices = choices_vector,
      selected = values$selected_node
    )

  })
}

#' Orgviz shiny app
#'
#' @param tg user supplied tbl_graph
#' @param df user supplied a data frame in org_tall_df format
#'  ie summarised metrics for the units in the network as generated by calc_summary_df.
#'
#' @return runs a shiny app
#' @export
#' @import shiny
#'
#' @examples
#' NULL
orgviz <- function(tg=NULL, df=NULL) {
  shinyApp(ui = orgviz_ui(),
           server = function(input, output) {
             orgviz_server(input, output, tg=tg, df=df)
           }
  )
}

